<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../pack.targets"/>
	
	<PropertyGroup>
		<TargetFramework>$(GenFrwkVer)</TargetFramework>

		<IncludeBuildOutput>false</IncludeBuildOutput>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

		<NoWarn>$(NoWarn);NU5128</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="../AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="../AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="RoyalCode.SmartCommands.Tests" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="$(CodeAnalysisVer)" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="$(CodeAnalysisVer)" PrivateAssets="all" />
	</ItemGroup>
		
	<ItemGroup>
		<!-- Package Reference - FOR PUBLISH -->
		<PackageReference Include="RoyalCode.Extensions.SourceGenerator" Version="$(ExSrcGenVer)" />
		<!-- Project Reference - FOR TESTS - SMART MAPPER -->
<!--		<ProjectReference Include="..\..\..\utils\RoyalCode.Utils\RoyalCode.Extensions.SourceGenerator\RoyalCode.Extensions.SourceGenerator.csproj" />-->
	</ItemGroup>

	<Target BeforeTargets="Build" Name="Generator">
		<!-- Package items -->
		<ItemGroup>
			<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
			<Analyzer Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
			<None Include="$(NuGetPackageRoot)royalcode.extensions.sourcegenerator\$(ExSrcGenVer)\lib\netstandard2.0\RoyalCode.Extensions.SourceGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		</ItemGroup>
	</Target>

	<ItemGroup>
		<!-- Package items -->
		<None Include="RoyalCode.SmartCommands.Generators.props" Pack="true" PackagePath="build" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="RoyalCode.Extensions.SourceGenerator" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Generators" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Generators.Commands" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Descriptors" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Descriptors.Assignments" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Descriptors.PropertySelection" />
	</ItemGroup>
</Project>
