<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>

		<IncludeBuildOutput>false</IncludeBuildOutput>
		<EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>

		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>

		<Version>0.1.0</Version>
		<AssemblyVersion>0.1.0</AssemblyVersion>
		<FileVersion>0.1.0</FileVersion>

		<NoWarn>$(NoWarn);NU5128</NoWarn>
	</PropertyGroup>

	<ItemGroup>
		<AdditionalFiles Include="../AnalyzerReleases.Shipped.md" />
		<AdditionalFiles Include="../AnalyzerReleases.Unshipped.md" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.CodeAnalysis.Analyzers" Version="4.14.0" PrivateAssets="all" />
		<PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" PrivateAssets="all" />
	</ItemGroup>
		
	<ItemGroup>
		<!-- Package Reference - FOR PUBLISH -->
		<!--<PackageReference Include="RoyalCode.Extensions.SourceGenerator" Version="0.1.0" />-->
		<!-- Project Reference - FOR TESTS - SMART MAPPER -->
		<ProjectReference Include="..\..\..\utils\RoyalCode.Utils\RoyalCode.Extensions.SourceGenerator\RoyalCode.Extensions.SourceGenerator.csproj" />
	</ItemGroup>

	<Target BeforeTargets="Build" Name="Generator">
		<!-- Package items -->
		<ItemGroup>
			<None Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
			<Analyzer Include="$(OutputPath)\$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" />
			<None Include="$(NuGetPackageRoot)royalcode.extensions.sourcegenerator\0.1.0\lib\netstandard2.0\RoyalCode.Extensions.SourceGenerator.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false" />
		</ItemGroup>
	</Target>

	<ItemGroup>
		<!-- Package items -->
		<None Include="RoyalCode.SmartCommands.Generators.props" Pack="true" PackagePath="build" Visible="false" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="RoyalCode.Extensions.SourceGenerator" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Generators" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Generators.Commands" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Descriptors" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Descriptors.Assignments" />
		<Using Include="RoyalCode.Extensions.SourceGenerator.Descriptors.PropertySelection" />
	</ItemGroup>
</Project>
