<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DemoFrwkVer)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="Infra\Security\" />
	  <Folder Include="Handlers\" />
	  <Folder Include="Web\" />
	</ItemGroup>

	<Import Project="../demo.targets" />

</Project>
