<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>$(DemoFrwkVer)</TargetFrameworks>
	</PropertyGroup>

	<ItemGroup>
	  <Folder Include="Infra\Security\" />
	  <Folder Include="Handlers\" />
	</ItemGroup>

	<ItemGroup>
	  <None Include=".docs\seguranca-docs.md" />
	  <None Include=".docs\seguranca-plan.md" />
	</ItemGroup>

	<Import Project="../demo.targets" />

</Project>
