using System.Collections.Immutable;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using RoyalCode.SmartCommands.Generators.Generators;
using RoyalCode.SmartCommands.WorkContext.Options;
using RoyalCode.SmartCommands.Tests.Models;

namespace RoyalCode.SmartCommands.Tests;

internal static class Util
{
    private const string GeneratedFileHeader = "// <auto-generated/>\r\n#nullable enable\r\n";
    private const string MemberNotNullSuppression =
        "#pragma warning disable CS8774 // WasValidated asserts an invariant established by the generated handler.\r\n";
    private const string ImplicitUsings =
        "global using System;\n" +
        "global using System.Collections.Generic;\n" +
        "global using System.IO;\n" +
        "global using System.Linq;\n" +
        "global using System.Net.Http;\n" +
        "global using System.Threading;\n" +
        "global using System.Threading.Tasks;\n";

    internal static string? GeneratedCode(string? body)
    {
        return body is null
            ? null
            : GeneratedFileHeader + "\r\n" + NormalizeLineEndings(body);
    }

    internal static string? GeneratedValidatedCode(string? body)
    {
        return body is null
            ? null
            : GeneratedFileHeader + MemberNotNullSuppression + "\r\n" + NormalizeLineEndings(body);
    }

    private static string NormalizeLineEndings(string value) =>
        value.Replace("\r\n", "\n").Replace("\n", "\r\n");

    internal static void Compile(
        string sourceCode,
        out Compilation outputCompilation,
        out ImmutableArray<Diagnostic> diagnostics)
    {
        var compilation = CreateCompilation(sourceCode);

        // apply the source generator and collect the output
        var driver = CSharpGeneratorDriver.Create(new IncrementalGenerator());

        driver.RunGeneratorsAndUpdateCompilation(compilation, out outputCompilation, out diagnostics);
    }

    /// <summary>
    /// Creates a compilation for <paramref name="sourceCode"/> with the same references used by
    /// <see cref="Compile"/>.
    /// </summary>
    internal static Compilation CreateCompilation(params string[] sourceCode)
    {
        var syntaxTrees = sourceCode
            .Select(ParseSource)
            .ToArray();

        var trustedPlatformAssemblies = ((string?)AppContext.GetData("TRUSTED_PLATFORM_ASSEMBLIES"))
            ?.Split(Path.PathSeparator)
            ?? [];

        // assemblies references requered to compile the source code
        var referencePaths = trustedPlatformAssemblies
            .Concat(Directory.GetFiles(AppContext.BaseDirectory, "*.dll"))
            .Concat(
            [
                typeof(Util).Assembly.Location,
                typeof(object).Assembly.Location,
                typeof(CommandHandlerGenerator).Assembly.Location,
                typeof(Enumerable).Assembly.Location,
                typeof(ICollection<>).Assembly.Location,
                typeof(CommandAttribute).Assembly.Location,
                typeof(RetryOnConcurrencyOptions).Assembly.Location,
                typeof(Microsoft.Extensions.Options.IOptions<>).Assembly.Location,
                typeof(RoyalCode.WorkContext.IWorkContext).Assembly.Location,
                typeof(RoyalCode.SmartProblems.Result).Assembly.Location,
                typeof(Task).Assembly.Location,
                typeof(CancellationToken).Assembly.Location,
                typeof(Produto).Assembly.Location
            ])
            .Where(File.Exists)
            .Distinct(StringComparer.OrdinalIgnoreCase);

        var references = referencePaths.Select(path => MetadataReference.CreateFromFile(path));

        // create a compilation for the source code.
        return CSharpCompilation.Create(
            "SourceGeneratorTests",
            syntaxTrees,
            references,
            new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));
    }

    internal static SyntaxTree ParseSource(string sourceCode) =>
        CSharpSyntaxTree.ParseText(ImplicitUsings + sourceCode);

    /// <summary>
    /// Creates a <see cref="GeneratorDriver"/> that tracks incremental steps, so tests can assert caching
    /// (<c>Cached</c>/<c>Unchanged</c>) and symbol-free retention across runs.
    /// </summary>
    internal static GeneratorDriver CreateTrackedDriver() =>
        CSharpGeneratorDriver.Create(
            generators: [new IncrementalGenerator().AsSourceGenerator()],
            additionalTexts: default,
            parseOptions: null,
            optionsProvider: null,
            driverOptions: new GeneratorDriverOptions(IncrementalGeneratorOutputKind.None, trackIncrementalGeneratorSteps: true));

    /// <summary>
    /// Runs the generator once over <paramref name="sourceCode"/> with step tracking enabled and returns the
    /// resulting driver (for a follow-up incremental run) and the run result (for inspecting tracked steps).
    /// </summary>
    internal static (GeneratorDriver Driver, GeneratorDriverRunResult Result) RunTracked(string sourceCode)
    {
        var compilation = CreateCompilation(sourceCode);
        var driver = CreateTrackedDriver().RunGenerators(compilation);
        return (driver, driver.GetRunResult());
    }
}

// template for the code snippets
file static class Code
{
    public const string Command =
"""
using RoyalCode.SmartCommands;
using RoyalCode.SmartProblems;
using RoyalCode.SmartValidations;

namespace Tests.Scenarios.Ds;

""";
    
    public const string Interface =
"""
using RoyalCode.SmartProblems;

namespace Tests.Scenarios.Ds;

""";
    
    public const string Handler =
"""
using RoyalCode.SmartCommands;
using RoyalCode.SmartProblems;
using Tests.Scenarios.Ds;

namespace Tests.Scenarios.Ds.Internals;

""";
}
