<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.20" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="8.1.4" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="RoyalCode.SmartProblems.ApiResults" Version="$(SmartProblemsVer)" />
		<PackageReference Include="RoyalCode.SmartProblems.Http" Version="$(SmartProblemsVer)" />
		<PackageReference Include="RoyalCode.WorkContext.EntityFramework" Version="$(WorkContextVer)" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\RoyalCode.SmartCommands.Tests.Models\RoyalCode.SmartCommands.Tests.Models.csproj" />
		<ProjectReference Include="..\RoyalCode.SmartCommands.WorkContext\RoyalCode.SmartCommands.WorkContext.csproj" />
		<ProjectReference Include="..\RoyalCode.SmartCommands\RoyalCode.SmartCommands.csproj" />
		<ProjectReference Include="..\RoyalCode.SmartCommands.Generators\RoyalCode.SmartCommands.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>

	<ItemGroup>
		<!-- Package Reference - FOR PUBLISH -->
		<PackageReference Include="RoyalCode.Extensions.SourceGenerator" Version="$(ExSrcGenVer)" ReferenceOutputAssembly="false" />
		<!-- Project Reference - FOR TESTS - SMART MAPPER -->
		<!-- <ProjectReference Include="..\..\..\utils\RoyalCode.Utils\RoyalCode.Extensions.SourceGenerator\RoyalCode.Extensions.SourceGenerator.csproj" ReferenceOutputAssembly="false" />-->
	</ItemGroup>
	<ItemGroup>
		<!-- Package Reference - FOR PUBLISH -->
		<Analyzer Include="$(NuGetPackageRoot)royalcode.extensions.sourcegenerator\$(ExSrcGenVer)\lib\netstandard2.0\RoyalCode.Extensions.SourceGenerator.dll" />
		<!-- Project Reference - FOR TESTS - SMART MAPPER -->
		<!-- <Analyzer Include="..\..\..\utils\RoyalCode.Utils\RoyalCode.Extensions.SourceGenerator\bin\Debug\netstandard2.0\RoyalCode.Extensions.SourceGenerator.dll" />-->
	</ItemGroup>

	<PropertyGroup>
		<EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
		<CompilerGeneratedFilesOutputPath>Generated</CompilerGeneratedFilesOutputPath>
	</PropertyGroup>

	<ItemGroup>
		<!-- Exclude the output of source generators from the compilation -->
		<Compile Remove="$(CompilerGeneratedFilesOutputPath)/**/*.cs" />
		<None Include="Generated/**" Visible="true" />
		<Compile Remove="Generated\RoyalCode.SmartCommands.Generators\**" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Generated\RoyalCode.SmartCommands.Generators\" />
	</ItemGroup>
</Project>
