using System.Text;

namespace RoyalCode.SmartCommands.Generators.Generators;

internal static class GeneratedFileHeader
{
    public static void AddTo(ClassGenerator generator, bool suppressMemberNotNullWarning = false)
    {
        generator.Generating += (_, builder) => Write(builder, suppressMemberNotNullWarning);
    }

    /// <summary>Escreve o cabeçalho padrão diretamente em um builder (para geradores sem evento Generating).</summary>
    public static void WriteTo(StringBuilder builder) => Write(builder, suppressMemberNotNullWarning: false);

    private static void Write(StringBuilder builder, bool suppressMemberNotNullWarning)
    {
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        if (suppressMemberNotNullWarning)
            builder.AppendLine("#pragma warning disable CS8774 // WasValidated asserts an invariant established by the generated handler.");
        builder.AppendLine();
    }
}
