using System.Diagnostics.CodeAnalysis;

namespace RoyalCode.SmartCommands;

/// <summary>
/// <para>
///     Maps a command class to an HTTP <c>GET</c> endpoint intended to find (retrieve) a single entity by its identifier.
/// </para>
/// <para>
///     This attribute require a service of <see cref="IRepositoryAccessor{TEntity}"/> 
///     to be available via Dependency Injection.
/// </para>
/// <para>
///     Combine it with <see cref="EntityReferenceAttribute{TEntity, TId}"/>
///     to declare which entity will be loaded before executing the command logic.
/// </para>
/// <para>
///     You may group the endpoint with <see cref="MapGroupAttribute"/>, add metadata using
///     <see cref="WithDescriptionAttribute"/> and <see cref="WithSummaryAttribute"/>, and enforce security via
///     <see cref="WithAuthorizationAttribute"/> or <see cref="WithPolicyAttribute"/>.
/// </para>
/// <para>
///     Endpoint handler code is generated by <see cref="MapApiHandlersAttribute"/> in a static partial class.
/// </para>
/// <para>Example:</para>
/// <para>
/// <code>
/// // Find a product by id returning the ProductDetails DTO
/// [MapGroup("api/products")]
/// [MapFind("/{id}:int", "find-product")]
/// [EntityReference{Product, int}]
/// public class ProductDetails
/// {
///     public int Id { get; set; }
///     public string Name { get; set; }
///     public bool Active { get; set; }
/// }
/// </code>
/// </para>
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public class MapFindAttribute : Attribute
{
    /// <summary>
    /// Maps an endpoint to find (retrieve) a specific entity by its identifier.
    /// </summary>
    /// <param name="endpointRoutePattern">
    ///     The route pattern for the endpoint, e.g. <c>"/{id}"</c>.
    /// </param>
    /// <param name="endpointName">
    ///     A unique endpoint name, e.g. <c>"find-product"</c>.
    /// </param>
    public MapFindAttribute([StringSyntax("Route")] string endpointRoutePattern, string endpointName) { }
}
