using System.Diagnostics.CodeAnalysis;

namespace RoyalCode.SmartCommands;

/// <summary>
/// <para>
///     Maps a DTO class to an HTTP <c>GET</c> endpoint that finds (retrieves) a single entity by an
///     alternate or composite key — one or more direct properties of <typeparamref name="TEntity"/> — and
///     projects it into the decorated DTO type. Unlike <see cref="MapFindAttribute"/>, which finds by the
///     entity identifier, this attribute finds by named properties.
/// </para>
/// <para>
///     This attribute requires a service of <see cref="IRepositoryAccessor{TEntity}"/> to be available via
///     Dependency Injection. The projection is executed by the provider, without materializing or tracking
///     the entity, and the not-found problem names the entity and lists the search criteria.
/// </para>
/// <para>
///     Each property declared in <c>propertyNames</c> (prefer <c>nameof</c>) must be a direct, public and
///     readable property of <typeparamref name="TEntity"/>, and must be matched — case-insensitively — by a
///     route placeholder of the same name; the generator derives the parameter type from the property. The
///     search combines the criteria with <c>AND</c>, in declaration order (used to build the not-found
///     problem). Missing, duplicated, unknown, non-readable or incompatible properties/placeholders are
///     reported at compile time (RCCMD056).
/// </para>
/// <para>
///     You may group the endpoint with <see cref="MapGroupAttribute"/>, add metadata using
///     <see cref="WithDescriptionAttribute"/>, <see cref="WithSummaryAttribute"/> and
///     <see cref="WithTagsAttribute"/>, add endpoint filters with <see cref="WithEndpointFilterAttribute{TFilter}"/>
///     and enforce security via <see cref="WithAuthorizationAttribute"/> or <see cref="WithPolicyAttribute"/>.
/// </para>
/// <para>
///     Endpoint handler code is generated by <see cref="MapApiHandlersAttribute"/> in a static partial class.
/// </para>
/// <para>Example — simple alternate key (SKU):</para>
/// <para>
/// <code>
/// [MapGroup("api/produtos")]
/// [MapFindBy&lt;Produto&gt;("por-sku/{sku}", "produto-por-sku", nameof(Produto.Sku))]
/// public class ProdutoDetalhes
/// {
///     public int Id { get; set; }
///     public string Sku { get; set; }
///     public string Nome { get; set; }
/// }
/// </code>
/// </para>
/// <para>Example — composite key:</para>
/// <para>
/// <code>
/// [MapGroup("api/itens")]
/// [MapFindBy&lt;ItemPedido&gt;("{pedidoId:guid}/{numero:int}", "item-do-pedido",
///     nameof(ItemPedido.PedidoId), nameof(ItemPedido.Numero))]
/// public class ItemPedidoDetalhes { /* ... */ }
/// </code>
/// </para>
/// </summary>
/// <typeparam name="TEntity">The entity type searched by the alternate/composite key.</typeparam>
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public class MapFindByAttribute<TEntity> : Attribute
    where TEntity : class
{
    /// <summary>
    /// Maps an endpoint to find (retrieve) a specific entity by an alternate or composite key.
    /// </summary>
    /// <param name="endpointRoutePattern">
    ///     The route pattern for the endpoint, with a named placeholder for each declared property,
    ///     e.g. <c>"por-sku/{sku}"</c>. When the class declares <see cref="MapGroupAttribute"/>, the group
    ///     prefix is prepended.
    /// </param>
    /// <param name="endpointName">
    ///     A unique endpoint name, e.g. <c>"produto-por-sku"</c>.
    /// </param>
    /// <param name="propertyNames">
    ///     The names of the direct properties of <typeparamref name="TEntity"/> that form the key, matched
    ///     (case-insensitively) to the named placeholders of the route pattern. Prefer declaring them with
    ///     <c>nameof</c>. The order is preserved to build the not-found problem.
    /// </param>
    public MapFindByAttribute(
        [StringSyntax("Route")] string endpointRoutePattern,
        string endpointName,
        params string[] propertyNames)
    { }
}
