using System.Diagnostics.CodeAnalysis;

namespace RoyalCode.SmartCommands;

/// <summary>
/// <para>
///     Maps a command class to an HTTP <c>GET</c> endpoint that performs a search or listing operation (paged, filtered, etc.).
/// </para>
/// <para>
///     Combine with <see cref="SearchReferenceAttribute{TEntity, TModel}"/> or <see cref="SearchReferenceAttribute{TEntity}"/>
///     for entity-based search scenarios.
/// </para>
/// <para>
///     Group related endpoints using <see cref="MapGroupAttribute"/>, document them with <see cref="WithDescriptionAttribute"/>
///     and <see cref="WithSummaryAttribute"/>, and secure with <see cref="WithAuthorizationAttribute"/> or
///     <see cref="WithPolicyAttribute"/>.
/// </para>
/// <para>
///     Endpoint handler code is generated by <see cref="MapApiHandlersAttribute"/>.
/// </para>
/// <para>Example:</para>
/// <para>
/// <code>
/// // Search products with simple filter and return paged results of ProductDetails DTO.
/// [MapGroup("api/products")]
/// [MapSearch("/", "search-products")]
/// [SearchReference{Product, ProductDetails}]
/// public class SearchProducts
/// {
///     public string? Name { get; set; }
///     public bool? Active { get; set; }
/// }
/// </code>
/// </para>
/// </summary>
[AttributeUsage(AttributeTargets.Class, Inherited = false)]
public class MapSearchAttribute : Attribute
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MapSearchAttribute"/> class.
    /// </summary>
    /// <param name="endpointRoutePattern">
    ///     The route pattern for the search endpoint, commonly <c>"/"</c> or a sub-path like <c>"/active"</c>.
    /// </param>
    /// <param name="endpointName">
    ///     A unique name for the endpoint, e.g. <c>"search-products"</c>.
    /// </param>
    public MapSearchAttribute([StringSyntax("Route")] string endpointRoutePattern, string endpointName) { }
}

