<Project Sdk="Microsoft.NET.Sdk">

	<Import Project="../pack.targets"/>
	
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="RoyalCode.SmartProblems" Version="$(SmartProblemsVer)" />
		<PackageReference Include="RoyalCode.SmartValidations" Version="$(SmartValidationsVer)"/>
	</ItemGroup>

</Project>
