<Project>
	<ItemGroup>
		<ProjectReference Include="..\RoyalCode.SmartCommands.WorkContext\RoyalCode.SmartCommands.WorkContext.csproj" />
		<ProjectReference Include="..\RoyalCode.SmartCommands\RoyalCode.SmartCommands.csproj" />
		<ProjectReference Include="..\RoyalCode.SmartCommands.Generators\RoyalCode.SmartCommands.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="RoyalCode.SmartSearch.AspNetCore" Version="$(SmartSearchVer)" />
		<PackageReference Include="RoyalCode.SmartProblems.ApiResults" Version="$(SmartProblemsVer)" />
		<PackageReference Include="RoyalCode.SmartProblems.Http" Version="$(SmartProblemsVer)" />
		<PackageReference Include="RoyalCode.WorkContext.EntityFramework" Version="$(WorkContextVer)" />
		<PackageReference Include="RoyalCode.SmartSelector" Version="$(SmartSelectVer)" />
		<PackageReference Include="RoyalCode.SmartSelector.Generators" Version="$(SmartSelectVer)" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(PGVer)" />
	</ItemGroup>
</Project>