<Project>
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup>
		<Authors>Royal Code</Authors>
		<Copyright>Royal Code Copyright ©  $([System.DateTime]::UtcNow.ToString("yyyy"))</Copyright>
		<RepositoryUrl>https://github.com/Royal-Code/SmartCommands</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<Configurations>Debug;Release</Configurations>
		<PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
	</PropertyGroup>
	<PropertyGroup>
		<SmartProblemsVer>1.0.0-preview-6.0</SmartProblemsVer>
		<SmartValidationsVer>1.0.0-preview-4.0</SmartValidationsVer>
		<WorkContextVer>0.8.6</WorkContextVer>
		<SmartSearchVer>0.9.0</SmartSearchVer>
		<SmartSelectVer>0.4.0</SmartSelectVer>
		<ExSrcGenVer>0.1.13</ExSrcGenVer>
	</PropertyGroup>
</Project>
