<Project>
	<PropertyGroup>
		<LibFrwkVer>net8.0;net9.0;net10.0</LibFrwkVer>
		<TestFrwkVer>net10.0</TestFrwkVer>
		<DemoFrwkVer>net10.0</DemoFrwkVer>
		<GenFrwkVer>netstandard2.0</GenFrwkVer>
	</PropertyGroup>
	<PropertyGroup>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
	</PropertyGroup>
	<PropertyGroup>
		<Authors>Royal Code</Authors>
		<Copyright>Royal Code Copyright ©  $([System.DateTime]::UtcNow.ToString("yyyy"))</Copyright>
		<RepositoryUrl>https://github.com/Royal-Code/SmartCommands</RepositoryUrl>
		<RepositoryType>Git</RepositoryType>
		<Configurations>Debug;Release</Configurations>
		<PackageLicenseExpression>AGPL-3.0-only</PackageLicenseExpression>
	</PropertyGroup>
	<PropertyGroup>
		<SmartProblemsVer>1.0.0-preview-7.0</SmartProblemsVer>
		<SmartValidationsVer>1.0.0-preview-7.0</SmartValidationsVer>
		<WorkContextVer>0.9.0</WorkContextVer>
		<SmartSearchVer>0.11.0</SmartSearchVer>
		<SmartSelectVer>0.5.1</SmartSelectVer>
		<ExSrcGenVer>0.3.0</ExSrcGenVer>
	</PropertyGroup>
	<PropertyGroup>
		<CodeAnalysisVer>4.14.0</CodeAnalysisVer>
		<PGVer>10.0.0</PGVer>
		<SwashbuckleVer>10.2.3</SwashbuckleVer>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<AspVer>8.0.11</AspVer>
		<ExtVer>8.0.2</ExtVer>
		<EFVer>8.0.11</EFVer>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net9.0'">
		<AspVer>9.0.0</AspVer>
		<ExtVer>9.0.0</ExtVer>
		<EFVer>9.0.0</EFVer>
	</PropertyGroup>
	<PropertyGroup Condition="'$(TargetFramework)' == 'net10.0'">
		<AspVer>10.0.0</AspVer>
		<ExtVer>10.0.0</ExtVer>
		<EFVer>10.0.0</EFVer>
	</PropertyGroup>
</Project>
